name: Simple-V-Blockchain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install V
      run: |
        git clone https://github.com/vlang/v
        cd v
        make
    - name: build Blockchain
      run: ./v/v .
